export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  STOCK_ALREADY_EXISTS: 'STOCK_ALREADY_EXISTS',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STOCK_LIMITS: 'INVALID_STOCK_LIMITS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
